# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  ctype: en_US.utf8
  collation: en_US.utf8
  template: template0

development:
  <<: *default
  database: kraud-app_development

test:
  <<: *default
  database: kraud-app_test

production:
  <<: *default
  database: kraud-app_production
  username: dmitry
  password: dmitry
